---
- name: Gather OS specific variables for role phpmyadmin
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"

- name: Ensure phpmyadmin is installed.
  package:
    name: "{{ phpmyadmin_package }}"
    state: present
  tags:
    - packages
